### ISSUE TITLE
how does bot handle 0 gold

### ISSUE THREAD

**Issue by gomsnothereman** [Phr33d0m/NW-Profession-Bot#179]
I noticed today that the bot does not handle having no gold well, on alchemy i set it to do like 6 slots worth, and it was often only using 1 or 2 or even NONE (on one character) and i think the reason is, they didn't have enough gold to buy coal even,

Is the bot smart enough to do like gather tasks and sell the results, until it can buy the necessary resources from the shop, to do the level tasks???

**Comment by Phr33d0m** [comment]
The bot will gather only necessary items for other tasks to be completed. The bot will not sell random (and by random I mean stuff you haven't selected in the Vendor tab) items in order to gather gold to buy assets (like coal). The bot is _smart enough_, but like every piece of technology **it does what you tell it to do, not what you want it to do**.

Anyhow, AFAIR the bot will tell you if some character is missing an asset with the message "Please buy X for Y@Z".

If the bot gets stuck that's a real issue, although **if the bot does 0 tasks because that character lacks gold then it's your problem to supply it with it beforehand**.
