### ISSUE TITLE
Issues with allocating new M9 tasks

### ISSUE THREAD

**Issue by ketacz** [Phr33d0m/NW-Profession-Bot#219]
Hello,

Need a bit of help here.
I'm trying to set to have the weaponsmithing task to create surplus eq crates for SH.

Unfortunately I can't seem to make it work correctly. So I've took the task name (Weaponsmithing_Voucher_Gear_T3) and wiped everything from the "mass refining" profile. I set only the above mentioned task to be added on lvl 17 - I'm at lvl 20 on the profession. 

Unfortunately the script still makes me an iron dagger +1 even though this task is NOT listed on the remade profile.
I have per slot task allocation set and it still does not work correctly.

I've added the SH AD crate to the Leadership profile and it works like a charm...what am I making wrong?

This is how it looks for me:

  addProfile("Weaponsmithing", {
        profileName: "mass refining",
        isProfileActive: true,
        useMassTask: true,
        level: {
            17: ["Weaponsmithing_Voucher_Gear_T3"],  
        },
    });

and on working Leadership:

 addProfile('Leadership',{
        "profileName": "RP (Stacked Assets)",
            "level": {

```
            "25": [
                "Leadership_Tier4_24_Wizardsseneschal", // Escort a Wizard's Seneschal (Resonant Bag) 16h
                "Leadership_Tier4_22r_Capturebandithq", // Capture Bandit Leader (Resonant Bag) Rare 8h
                "Leadership_Tier4_24r_Killdragon", // Kill a Young Dragon (Resonant Bag) Rare 12h
                "Leadership_Voucher_Ad_T4", // SH AD Crate 6h
                "Leadership_Tier4_22_Guardclerics", // Guard Clerics of Ilmater (Artifact Paraphenalia) 8h
                "Leadership_Tier4_21_Protectmagic", // Protect Magical Goods Market (Bandit Camp Clue, Thaumaturgic Bag) 12h
            ]
        }
```

I must add that Syntax does not show any errors on the lines. So I'm puzzled what's wrong.

**Comment by ketacz** [comment]
I've also tried to add a clean/new profile for this one task alone. 
Of course I took the existing/working ones as an example but this just stopped script from running.

I'm sure I'm making something wrong, just no clue what it is :)

**Comment by noonereally** [comment]
Look at my post here, though it's for the custom profiles:
https://greasyfork.org/en/forum/discussion/8633/x

For what you tried to do:
In Weaponsmithing you didn't select the right base profile, so the addProfile assumed the default profile. The default profile uses crafting to level up, and that's why you got the dagger.

Also you didn't put anything at level 20, so the 17 wont do anything at all.

Try something like:

```
addProfile("Weaponsmithing", {
profileName: "Pick a new name here",
isProfileActive: true,
useMassTask: true,
level: {
17: ["Weaponsmithing_Voucher_Gear_T3","+"],
18: "+6",
23:  ["Weaponsmithing_Voucher_Gear_T4","+"],
24:  ["Weaponsmithing_Voucher_Gear_T4","+"],
25:  ["Weaponsmithing_Voucher_Gear_T4","+"],

},
},"mass refining");
```

The + at the end of the level tell is to copy all the rest of the level from the base profile, in this case the mass refining profile. It will copy the refine and gather tasks.
the +6 tells it to copy the previous level to the next 6 levels so at level 20 you will get the same line as 17 and not the one from the base profile.

**Comment by ketacz** [comment]
Yeap, that worked! 

Thanks for help :)
