### ISSUE TITLE
Consuming too much RAM and CPU 

### ISSUE THREAD

**Issue by ozgurturk** [Phr33d0m/NW-Profession-Bot#229]
Hello,

I use multiple chrome and scripts but they consume too much cpu and ram. Is there a way to decrease that ?

**Comment by Phr33d0m** [comment]
The problem is Chrome, not this script. 

The actual footprint of the script should be waay less than 15MB even if you have all of your 50 characters with per-slot tasks and lots of custom profiles, etc...

I haven't tested but unless there's a memory leak somewhere it shouldn't consume more than that. Anyhow if there were a memory leak a proper report with what is causing it (or when) should be submitted.
