### ISSUE TITLE
leather working problems

### ISSUE THREAD

**Issue by fsdraconis** [Phr33d0m/NW-Profession-Bot#243]
Hello! Wanted to first thank you for your time and help with this program it has been very useful!

The leather working script from 20 to 25 is currently bugged. It will work fine working its way up to 20. But the moment you get to 20 it will suddenly stall up and not have a clue what to do. If you try to go in to pick jobs it pulls you right out to the over view window again. It will not go on to other characters.
I did try different profiles with no luck.

I also can not get profiles to work. I can create a leather working profile and get it imported. But it will not name it correctly and then it will add in the default profile into it as well.

If I knew how to rewrite the original profile I'd just fix it. But I don't know where it is.

**Comment by inv-github** [comment]
I don't see anything obviously wrong with the current Ornate pants task for 20+, but I did notice that sometimes the worker and task gets messed up permanently in the gateway.  After manually setting the next task and picking the worker manually, it seems to fix itself.

The creating new profiles is kind of non-intuitive until you do it right a couple times, at least for me.  The way that I got it working (not sure if it's the "correct" way) is to 
1. Pick the task name and base profile that I want to build off of, like leatherworking and default.
2. Click the button to the right of the dropdown to open the Profile window.  
3. Delete the top square bracket and the bottom closing square bracket.  
4. Make the changes that you want.  
5. Edit the "profileName" to be whatever, like "default2."  
6. Copy/paste the whole thing back to the large text area in the original "custom profiles" tab and close the profile window.  
7. Optionally, change the "base profile" dropdown to "new" and keep "task name" to leatherworking if you want a completely new profile.
8. Import.
9. If that works, then you should get a new dropdown selection instead of default and just select your default2 to fix whatever profile issue is happening.

There's probably a better/easier way but at least I got my custom profiles working.

If you want to just modify the original profile, it's here:
https://github.com/Phr33d0m/NW-Profession-Bot/blob/master/main.js#L1234

**Comment by fsdraconis** [comment]
Thank you for the help! I shall give that a try.

It would be nice if there was a way to edit a profile instead of importing all over again.

**Comment by inv-github** [comment]
Yeah, I'm not aware of any way to just edit a profile straight up.  But you can get back your own custom profile at least by using the button and then delete the old one after importing new changes.

**Comment by 3bagorion33** [comment]
Version 4,9,7 do not have any problems with leather. To edit the script, you can use tampermonkey panel. BTW, this is an easy way to update: remove all the old code and insert a new one. All settings and custom profiles are saved.

**Comment by fsdraconis** [comment]
Where can I find what the terms for the different profession crate orders are?
Right now interested in leather and platesmithing, But may want to add in new options down the road. Thank you again for the support!

**Comment by inv-github** [comment]
Not sure I understand the question.  You mean this: https://github.com/Phr33d0m/NW-Profession-Bot/blob/master/extra/tasks_list.js
?

I don't know if it's super up to date but it has most of the stuff.  If they add a new one, just look at the gateway url and it's the part after the last slash and manually parse it out to add to your custom profile (e.g. http://gateway.playneverwinter.com/#char(charname@accountname)/professions-tasks/Leatherworking/Leatherworking_Tier4_Gather_Special)

**Comment by fsdraconis** [comment]
Thanks! That is exactly what I was hoping to learn!

**Comment by Phr33d0m** [comment]
Closing as per #247
