### ISSUE TITLE
"Leadership XP" is broken

### ISSUE THREAD

**Issue by Phr33d0m** [Phr33d0m/NW-Profession-Bot#39]
Hi, there are lots of places in the code where we check vs. "Leadership" to do stuff. Now we have "Leadership XP" which won't match and the bot won't do lots of necessary stuff for that profession.

I do want to have the two different task lists but not the way it is now (like different professions).

Something like the following should we way better IMHO:

``` javascript
$Leadership = {all the AD oriented tasks};
$LeadershipXP = {all the XP oriented tasks};

if(user wants AD)
    definedTask["Leadership"] = $Leadership;
else if(user wants XP)
    definedTask["Leadership"] = $LeadershipXP;
```

And somewhere a checkbox or a switch so we know what the user wants.

**Comment by noonereally** [comment]
The check vs Leadership is for taskName and not taskListName, both those tasks are of the same 'type'
and leadership xp should pass all those checks.

_I'm using it right now and it works as it should and not broken, it does all the necessary stuff including buying assets / tools_

If you find anything specific that does not work, please post

The 'if' above will probably not work because it will set it globally and not per char.
I've posted a semi-working/concept solution in the #40 discussion.

**Comment by Phr33d0m** [comment]
You're right, just double-checked that it uses indeed taskName... it was late the other night and I saw taskListName a couple of times but that does a completely different thing.
