### ISSUE TITLE
Which encrypt method you use for NW -login?

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#89]
Hello.

This is just a question to know which encrypt method do you use for NW -password?
I do believe open source code is safe but my guild mates are not so confident to write NW- account on 3rd party script.

Thanks for answer.

**Comment by Phr33d0m** [comment]
@GeneralSheppard we don't have any encryption at all. Please conside the following (as per how encryption tends to work):
- The bot stores your login details in plaintext inside Tampermonkey's data storage.
- The bot only auto-writes your login details at the allowed `@include` URLs (e.g.: `http://gateway*.playneverwinter.com/*`)
- The bot doesn't send your login details to any 3rd party (you can check the code yourself if you want to make sure).
- We trust (to some point) the way Tampermonkey stores the data for each of your scripts individually (so no other script can access that data AFAIK).
- If we used any encryption to store your password, then in order to use it later for the auto-login function we'd have to decrypt it. This being an open-source code, everyone would be able to see how we encrypt and decrypt stuff - making the encryption quite useless.

I hope to have solved yours (and your guild mates' trusting issues :wink:). Re-open this if something's been unclear.
